import type { ContractInstallment, FinanceEntry, FinancialPayment, LeadSource, ProcessMovement, ProcessPhaseHistory, ScheduledEvent, WorkflowRun, WorkflowRunStep } from "@/types/app";
import { normalizedSourceType } from "@/lib/schedulingIntegrity";

type DatabaseRow = Record<string, unknown>;
const str = (v: unknown, d = "") => typeof v === "string" ? v : v == null ? d : String(v);
const opt = (v: unknown) => { const x = str(v).trim(); return x ? x : undefined; };
const num = (v: unknown, d = 0) => { const x = Number(v); return Number.isFinite(x) ? x : d; };
const bool = (v: unknown, d = false) => v == null ? d : typeof v === "boolean" ? v : ["true","1","yes"].includes(str(v).toLowerCase());
const json = (v: unknown): Record<string, unknown> | undefined => v && typeof v === "object" && !Array.isArray(v) ? v as Record<string, unknown> : undefined;
const date = (v: unknown) => opt(v)?.slice(0, 10);
const stamp = (v: unknown) => opt(v);
const archived = (r: DatabaseRow) => stamp(r.archived_at ?? r.archivedAt);

export function financeStatusFromDatabase(value: unknown): FinanceEntry["status"] {
  const v = str(value).toLowerCase();
  const map: Record<string, FinanceEntry["status"]> = {
    draft: "Pendente", pending: "Pendente", pendente: "Pendente",
    paid: "Pago", pago: "Pago", overdue: "Atrasado", atrasado: "Atrasado",
    cancelled: "Cancelado", canceled: "Cancelado", cancelado: "Cancelado",
    partially_paid: "Parcial", partial: "Parcial", parcial: "Parcial",
    archived: "Arquivado", arquivado: "Arquivado", renegotiated: "Renegociado", renegociado: "Renegociado",
    refunded: "Estornado", reversed: "Estornado", estornado: "Estornado",
    written_off: "Baixado como perda", baixado_como_perda: "Baixado como perda",
  };
  return map[v] ?? "Pendente";
}
export function financeStatusToDatabase(value: FinanceEntry["status"]): string {
  return ({ Pendente:"pending", Pago:"paid", Atrasado:"overdue", Cancelado:"cancelled", Parcial:"partially_paid", Arquivado:"archived", Renegociado:"renegotiated", Estornado:"refunded", "Baixado como perda":"written_off" } as const)[value];
}

export function mapWorkflowRunFromDatabase(r: DatabaseRow): WorkflowRun { return {
  id:str(r.id), organizationId:opt(r.organization_id ?? r.organizationId), workflowTemplateId:str(r.workflow_template_id ?? r.workflowTemplateId), processId:opt(r.process_id ?? r.processId), clientId:opt(r.client_id ?? r.clientId), leadId:opt(r.lead_id ?? r.leadId),
  status:str(r.status,"pending") as WorkflowRun["status"], currentStepOrder:num(r.current_step_order ?? r.currentStepOrder), startedAt:str(r.started_at ?? r.startedAt), completedAt:stamp(r.completed_at ?? r.completedAt), cancelledAt:stamp(r.cancelled_at ?? r.cancelledAt), startedBy:opt(r.started_by ?? r.startedBy), idempotencyKey:str(r.idempotency_key ?? r.idempotencyKey), metadata:json(r.metadata), createdAt:stamp(r.created_at), updatedAt:stamp(r.updated_at), archivedAt:archived(r), version:num(r.version)
}; }
export function mapWorkflowRunToDatabase(i: WorkflowRun, organizationId: string): DatabaseRow { return { id:i.id, organization_id:i.organizationId ?? organizationId, workflow_template_id:i.workflowTemplateId, process_id:i.processId ?? null, client_id:i.clientId ?? null, lead_id:i.leadId ?? null, status:i.status, current_step_order:i.currentStepOrder, started_at:i.startedAt, completed_at:i.completedAt ?? null, cancelled_at:i.cancelledAt ?? null, started_by:i.startedBy ?? null, idempotency_key:i.idempotencyKey, metadata:i.metadata ?? {}, version:i.version ?? 0, archived_at:i.archivedAt ?? null }; }

export function mapWorkflowRunStepFromDatabase(r: DatabaseRow): WorkflowRunStep { return {
  id:str(r.id), organizationId:opt(r.organization_id), workflowRunId:str(r.workflow_run_id ?? r.workflowRunId), workflowStepId:str(r.workflow_step_id ?? r.workflowStepId), taskId:opt(r.task_id ?? r.taskId), stepOrder:num(r.step_order ?? r.stepOrder), status:str(r.status,"pending") as WorkflowRunStep["status"], dependsOnStepId:opt(r.depends_on_step_id ?? r.dependsOnStepId), executionGroup:opt(r.execution_group ?? r.executionGroup), conditionType:opt(r.condition_type ?? r.conditionType), conditionPayload:json(r.condition_payload ?? r.conditionPayload), requiredApproverRole:opt(r.required_approver_role ?? r.requiredApproverRole), requiredDocumentType:opt(r.required_document_type ?? r.requiredDocumentType), slaDueAt:stamp(r.sla_due_at ?? r.slaDueAt), slaPausedAt:stamp(r.sla_paused_at ?? r.slaPausedAt), slaPausedMinutes:num(r.sla_paused_minutes ?? r.slaPausedMinutes), startedAt:stamp(r.started_at), completedAt:stamp(r.completed_at), skippedAt:stamp(r.skipped_at), blockedReason:opt(r.blocked_reason), result:json(r.result), createdAt:stamp(r.created_at), updatedAt:stamp(r.updated_at), archivedAt:archived(r), version:num(r.version)
}; }
export function mapWorkflowRunStepToDatabase(i: WorkflowRunStep, organizationId: string): DatabaseRow { return { id:i.id, organization_id:i.organizationId ?? organizationId, workflow_run_id:i.workflowRunId, workflow_step_id:i.workflowStepId, task_id:i.taskId ?? null, step_order:i.stepOrder, status:i.status, depends_on_step_id:i.dependsOnStepId ?? null, execution_group:i.executionGroup ?? null, condition_type:i.conditionType ?? null, condition_payload:i.conditionPayload ?? {}, required_approver_role:i.requiredApproverRole ?? null, required_document_type:i.requiredDocumentType ?? null, sla_due_at:i.slaDueAt ?? null, sla_paused_at:i.slaPausedAt ?? null, sla_paused_minutes:i.slaPausedMinutes ?? 0, started_at:i.startedAt ?? null, completed_at:i.completedAt ?? null, skipped_at:i.skippedAt ?? null, blocked_reason:i.blockedReason ?? null, result:i.result ?? {}, version:i.version ?? 0, archived_at:i.archivedAt ?? null }; }

export function mapProcessMovementFromDatabase(r: DatabaseRow): ProcessMovement {
  const provider = opt(r.provider);
  const sourceRaw = str(r.source || (provider ? "court_integration" : "manual"));
  const source = (["manual","simulation","court_integration","workflow"].includes(sourceRaw) ? sourceRaw : provider ? "court_integration" : "manual") as ProcessMovement["source"];
  return { id:str(r.id), organizationId:opt(r.organization_id), processId:str(r.process_id ?? r.processId), movementType:str(r.movement_type ?? r.movementType,"general"), title:str(r.title,"Movimentação"), description:opt(r.description), occurredAt:str(r.occurred_at ?? r.movement_at ?? r.occurredAt), source, externalId:opt(r.external_id ?? r.external_movement_id ?? r.externalId), visibility:str(r.visibility,"internal") === "client" ? "client" : "internal", createdBy:opt(r.created_by ?? r.createdBy), legacyProvider:provider, legacyRawPayload:json(r.raw_payload), createdAt:stamp(r.created_at), updatedAt:stamp(r.updated_at), archivedAt:archived(r) };
}
export function mapProcessMovementToDatabase(i: ProcessMovement, organizationId: string): DatabaseRow { return { id:i.id, organization_id:i.organizationId ?? organizationId, process_id:i.processId, movement_type:i.movementType, title:i.title, description:i.description ?? "", occurred_at:i.occurredAt, source:i.source, external_id:i.externalId ?? null, visibility:i.visibility, created_by:i.createdBy ?? null, provider:i.legacyProvider ?? (i.source === "court_integration" ? "court_integration" : null), external_movement_id:i.externalId ?? null, movement_at:i.occurredAt, raw_payload:i.legacyRawPayload ?? {}, archived_at:i.archivedAt ?? null }; }

export function mapProcessPhaseHistoryFromDatabase(r: DatabaseRow): ProcessPhaseHistory { return { id:str(r.id), organizationId:opt(r.organization_id), processId:str(r.process_id), previousPhase:str(r.previous_phase), newPhase:str(r.new_phase), changedBy:opt(r.changed_by), changedAt:str(r.changed_at), reason:str(r.reason), workflowRunId:opt(r.workflow_run_id), createdAt:stamp(r.created_at), updatedAt:stamp(r.updated_at), archivedAt:archived(r) }; }
export function mapProcessPhaseHistoryToDatabase(i: ProcessPhaseHistory, organizationId: string): DatabaseRow { return { id:i.id, organization_id:i.organizationId ?? organizationId, process_id:i.processId, previous_phase:i.previousPhase, new_phase:i.newPhase, changed_by:i.changedBy ?? null, changed_at:i.changedAt, reason:i.reason, workflow_run_id:i.workflowRunId ?? null, archived_at:i.archivedAt ?? null }; }

export function mapContractInstallmentFromDatabase(r: DatabaseRow): ContractInstallment { return { id:str(r.id), organizationId:opt(r.organization_id), contractId:str(r.contract_id), installmentNumber:num(r.installment_number), amountCents:num(r.amount_cents), dueDate:str(r.due_date).slice(0,10), status:str(r.status,"pending") as ContractInstallment["status"], financialEntryId:opt(r.financial_entry_id), createdAt:stamp(r.created_at), updatedAt:stamp(r.updated_at), archivedAt:archived(r) }; }
export function mapContractInstallmentToDatabase(i: ContractInstallment, organizationId: string): DatabaseRow { return { id:i.id, organization_id:i.organizationId ?? organizationId, contract_id:i.contractId, installment_number:i.installmentNumber, amount_cents:i.amountCents, due_date:i.dueDate, status:i.status, financial_entry_id:i.financialEntryId ?? null, archived_at:i.archivedAt ?? null }; }

export function mapFinancialPaymentFromDatabase(r: DatabaseRow): FinancialPayment { return { id:str(r.id), organizationId:opt(r.organization_id), financialEntryId:str(r.financial_entry_id), amountCents:num(r.amount_cents), paymentDate:str(r.payment_date).slice(0,10), paymentMethod:str(r.payment_method), reference:opt(r.reference), receiptId:opt(r.receipt_id), idempotencyKey:str(r.idempotency_key), createdBy:opt(r.created_by), cancelledAt:stamp(r.cancelled_at), cancellationReason:opt(r.cancellation_reason), createdAt:stamp(r.created_at), updatedAt:stamp(r.updated_at), archivedAt:archived(r) }; }
export function mapFinancialPaymentToDatabase(i: FinancialPayment, organizationId: string): DatabaseRow { return { id:i.id, organization_id:i.organizationId ?? organizationId, financial_entry_id:i.financialEntryId, amount_cents:i.amountCents, payment_date:i.paymentDate, payment_method:i.paymentMethod, reference:i.reference ?? null, receipt_id:i.receiptId ?? null, idempotency_key:i.idempotencyKey, created_by:i.createdBy ?? null, cancelled_at:i.cancelledAt ?? null, cancellation_reason:i.cancellationReason ?? null, archived_at:i.archivedAt ?? null }; }

export function mapScheduledEventFromDatabase(r: DatabaseRow): ScheduledEvent { return { id:str(r.id), organizationId:opt(r.organization_id), eventType:str(r.event_type,"manual"), sourceType:normalizedSourceType(str(r.source_type,"manual")) as ScheduledEvent["sourceType"], sourceId:opt(r.source_id), title:str(r.title), clientId:opt(r.client_id), processId:opt(r.process_id), responsibleId:opt(r.responsible_id), financeId:opt(r.finance_id), startsAt:stamp(r.starts_at), endsAt:stamp(r.ends_at), dueDate:date(r.due_date), amount:r.amount == null ? undefined : num(r.amount), location:opt(r.location), meetingLink:opt(r.meeting_link), status:str(r.status,"scheduled"), notes:opt(r.notes), clientVisible:bool(r.client_visible), visibility:str(r.visibility,"internal") as ScheduledEvent["visibility"], externalEventId:opt(r.external_event_id), recurrenceRule:opt(r.recurrence_rule), recurrenceSeriesId:opt(r.recurrence_series_id), recurrenceExceptionDate:date(r.recurrence_exception_date), timezone:opt(r.timezone), syncStatus:str(r.sync_status,"local") as ScheduledEvent["syncStatus"], lastSyncAt:stamp(r.last_sync_at), syncError:opt(r.sync_error), externalUpdatedAt:stamp(r.external_updated_at), version:num(r.version), createdAt:stamp(r.created_at), updatedAt:stamp(r.updated_at), archivedAt:archived(r) }; }
export function mapScheduledEventToDatabase(i: ScheduledEvent, organizationId: string): DatabaseRow { return { id:i.id, organization_id:i.organizationId ?? organizationId, event_type:i.eventType, source_type:normalizedSourceType(i.sourceType ?? "manual"), source_id:i.sourceId ?? null, title:i.title, client_id:i.clientId ?? null, process_id:i.processId ?? null, responsible_id:i.responsibleId ?? null, finance_id:i.financeId ?? null, starts_at:i.startsAt ?? null, ends_at:i.endsAt ?? null, due_date:i.dueDate ?? null, amount:i.amount ?? null, location:i.location ?? "", meeting_link:i.meetingLink ?? "", status:i.status, notes:i.notes ?? "", client_visible:Boolean(i.clientVisible), visibility:i.visibility ?? (i.clientVisible ? "client" : "internal"), external_event_id:i.externalEventId ?? null, recurrence_rule:i.recurrenceRule ?? null, recurrence_series_id:i.recurrenceSeriesId ?? null, recurrence_exception_date:i.recurrenceExceptionDate ?? null, timezone:i.timezone ?? "America/Fortaleza", sync_status:i.syncStatus ?? "local", last_sync_at:i.lastSyncAt ?? null, sync_error:i.syncError ?? null, external_updated_at:i.externalUpdatedAt ?? null, version:i.version ?? 0, archived_at:i.archivedAt ?? null }; }

export function mapLeadSourceFromDatabase(r: DatabaseRow): LeadSource { return { id:str(r.id), organizationId:opt(r.organization_id), provider:str(r.provider,"Outro"), sourceName:str(r.source_name ?? r.provider,"Fonte"), status:str(r.active === false ? "inactive" : r.status,"prepared") as LeadSource["status"], defaultArea:str(r.default_area,"Geral"), defaultResponsibleId:opt(r.default_responsible_id), isDefault:bool(r.is_default), active:r.active !== false, lastReceivedAt:stamp(r.last_received_at), createdAt:stamp(r.created_at), updatedAt:stamp(r.updated_at), archivedAt:archived(r) }; }
export function mapLeadSourceToDatabase(i: LeadSource, organizationId: string): DatabaseRow { return { id:i.id, organization_id:i.organizationId ?? organizationId, provider:i.provider, source_name:i.sourceName, status:i.status, default_area:i.defaultArea, default_responsible_id:i.defaultResponsibleId ?? null, is_default:Boolean(i.isDefault), active:i.active !== false, last_received_at:i.lastReceivedAt ?? null, archived_at:i.archivedAt ?? null }; }

export function mapFinanceEntryFromDatabase(r: DatabaseRow, clientName="Escritório"): FinanceEntry { return { id:str(r.id), type:str(r.type).toLowerCase()==="despesa"?"Despesa":"Receita", category:str(r.category), costCenter:opt(r.cost_center), bankAccount:opt(r.bank_account), clientId:opt(r.client_id), client:clientName, processId:opt(r.process_id), amount:num(r.amount), dueDate:str(r.due_date).slice(0,10), paidDate:date(r.paid_date ?? r.payment_date), paidAmount:num(r.paid_amount,0), status:financeStatusFromDatabase(r.status), method:str(r.method,"PIX") as FinanceEntry["method"], recurrence:opt(r.recurrence), installment:num(r.installment,1), installments:num(r.installments,1), attachment:opt(r.attachment ?? r.receipt_url), receiptNumber:opt(r.receipt_number), notes:opt(r.notes), sourceType:str(r.source_type,"manual") as FinanceEntry["sourceType"], sourceId:opt(r.source_id), sourceInstallmentId:opt(r.source_installment_id), contractId:opt(r.contract_id), costId:opt(r.cost_id), payrollId:opt(r.payroll_id), proposalId:opt(r.proposal_id), competencyDate:date(r.competency_date), version:num(r.version), cancelledAt:stamp(r.cancelled_at), renegotiationId:opt(r.renegotiation_id), createdAt:stamp(r.created_at), updatedAt:stamp(r.updated_at), archivedAt:archived(r) }; }
export function mapFinanceEntryToDatabase(i: FinanceEntry, organizationId: string, clientId: string | null): DatabaseRow { return { id:i.id, organization_id:organizationId, client_id:clientId, process_id:i.processId ?? null, type:i.type==="Despesa"?"despesa":"receita", category:i.category, cost_center:i.costCenter ?? "", bank_account:i.bankAccount ?? "", amount:i.amount, due_date:i.dueDate || null, paid_date:i.paidDate ?? null, paid_amount:i.paidAmount ?? 0, status:financeStatusToDatabase(i.status), method:i.method, recurrence:i.recurrence ?? "", installment:i.installment ?? 1, installments:i.installments ?? 1, attachment:i.attachment ?? "", receipt_number:i.receiptNumber ?? null, notes:i.notes ?? "", source_type:i.sourceType ?? "manual", source_id:i.sourceId ?? null, source_installment_id:i.sourceInstallmentId ?? null, contract_id:i.contractId ?? null, cost_id:i.costId ?? null, payroll_id:i.payrollId ?? null, proposal_id:i.proposalId ?? null, competency_date:i.competencyDate ?? null, version:i.version ?? 0, cancelled_at:i.cancelledAt ?? null, renegotiation_id:i.renegotiationId ?? null, archived_at:i.archivedAt ?? null }; }
